// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: identity/identity/uniquekey.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Uniquekey struct {
	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Unikey []byte `protobuf:"bytes,2,opt,name=unikey,proto3" json:"unikey,omitempty"`
}

func (m *Uniquekey) Reset()         { *m = Uniquekey{} }
func (m *Uniquekey) String() string { return proto.CompactTextString(m) }
func (*Uniquekey) ProtoMessage()    {}
func (*Uniquekey) Descriptor() ([]byte, []int) {
	return fileDescriptor_5cad3cb1ec98c171, []int{0}
}
func (m *Uniquekey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Uniquekey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Uniquekey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Uniquekey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uniquekey.Merge(m, src)
}
func (m *Uniquekey) XXX_Size() int {
	return m.Size()
}
func (m *Uniquekey) XXX_DiscardUnknown() {
	xxx_messageInfo_Uniquekey.DiscardUnknown(m)
}

var xxx_messageInfo_Uniquekey proto.InternalMessageInfo

func (m *Uniquekey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Uniquekey) GetUnikey() []byte {
	if m != nil {
		return m.Unikey
	}
	return nil
}

func init() {
	proto.RegisterType((*Uniquekey)(nil), "identity.identity.Uniquekey")
}

func init() { proto.RegisterFile("identity/identity/uniquekey.proto", fileDescriptor_5cad3cb1ec98c171) }

var fileDescriptor_5cad3cb1ec98c171 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcc, 0x4c, 0x49, 0xcd,
	0x2b, 0xc9, 0x2c, 0xa9, 0xd4, 0x87, 0x33, 0x4a, 0xf3, 0x32, 0x0b, 0x4b, 0x53, 0xb3, 0x53, 0x2b,
	0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04, 0x61, 0x32, 0x7a, 0x30, 0x86, 0x92, 0x29, 0x17,
	0x67, 0x28, 0x4c, 0x95, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x88, 0x29, 0x24, 0xc6, 0xc5, 0x56, 0x9a, 0x97, 0x09, 0x12, 0x64, 0x52, 0x60, 0xd4,
	0xe0, 0x09, 0x82, 0xf2, 0x9c, 0x8c, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1,
	0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21,
	0x4a, 0x12, 0x6e, 0x7b, 0x05, 0xc2, 0x21, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0x60, 0x57,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x34, 0x8f, 0xe9, 0xb7, 0xaa, 0x00, 0x00, 0x00,
}

func (m *Uniquekey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Uniquekey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Uniquekey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Unikey) > 0 {
		i -= len(m.Unikey)
		copy(dAtA[i:], m.Unikey)
		i = encodeVarintUniquekey(dAtA, i, uint64(len(m.Unikey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintUniquekey(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUniquekey(dAtA []byte, offset int, v uint64) int {
	offset -= sovUniquekey(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Uniquekey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovUniquekey(uint64(l))
	}
	l = len(m.Unikey)
	if l > 0 {
		n += 1 + l + sovUniquekey(uint64(l))
	}
	return n
}

func sovUniquekey(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUniquekey(x uint64) (n int) {
	return sovUniquekey(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Uniquekey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUniquekey
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Uniquekey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Uniquekey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniquekey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniquekey
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniquekey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unikey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniquekey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthUniquekey
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthUniquekey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Unikey = append(m.Unikey[:0], dAtA[iNdEx:postIndex]...)
			if m.Unikey == nil {
				m.Unikey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUniquekey(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUniquekey
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUniquekey(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUniquekey
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniquekey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniquekey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUniquekey
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUniquekey
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUniquekey
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUniquekey        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUniquekey          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUniquekey = fmt.Errorf("proto: unexpected end of group")
)
