// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: identity/identity/query.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName       = "/identity.identity.Query/Params"
	Query_Id_FullMethodName           = "/identity.identity.Query/Id"
	Query_IdAll_FullMethodName        = "/identity.identity.Query/IdAll"
	Query_Uniquekey_FullMethodName    = "/identity.identity.Query/Uniquekey"
	Query_UniquekeyAll_FullMethodName = "/identity.identity.Query/UniquekeyAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Id items.
	Id(ctx context.Context, in *QueryGetIdRequest, opts ...grpc.CallOption) (*QueryGetIdResponse, error)
	IdAll(ctx context.Context, in *QueryAllIdRequest, opts ...grpc.CallOption) (*QueryAllIdResponse, error)
	// Queries a list of Uniquekey items.
	Uniquekey(ctx context.Context, in *QueryGetUniquekeyRequest, opts ...grpc.CallOption) (*QueryGetUniquekeyResponse, error)
	UniquekeyAll(ctx context.Context, in *QueryAllUniquekeyRequest, opts ...grpc.CallOption) (*QueryAllUniquekeyResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Id(ctx context.Context, in *QueryGetIdRequest, opts ...grpc.CallOption) (*QueryGetIdResponse, error) {
	out := new(QueryGetIdResponse)
	err := c.cc.Invoke(ctx, Query_Id_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IdAll(ctx context.Context, in *QueryAllIdRequest, opts ...grpc.CallOption) (*QueryAllIdResponse, error) {
	out := new(QueryAllIdResponse)
	err := c.cc.Invoke(ctx, Query_IdAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Uniquekey(ctx context.Context, in *QueryGetUniquekeyRequest, opts ...grpc.CallOption) (*QueryGetUniquekeyResponse, error) {
	out := new(QueryGetUniquekeyResponse)
	err := c.cc.Invoke(ctx, Query_Uniquekey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UniquekeyAll(ctx context.Context, in *QueryAllUniquekeyRequest, opts ...grpc.CallOption) (*QueryAllUniquekeyResponse, error) {
	out := new(QueryAllUniquekeyResponse)
	err := c.cc.Invoke(ctx, Query_UniquekeyAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Id items.
	Id(context.Context, *QueryGetIdRequest) (*QueryGetIdResponse, error)
	IdAll(context.Context, *QueryAllIdRequest) (*QueryAllIdResponse, error)
	// Queries a list of Uniquekey items.
	Uniquekey(context.Context, *QueryGetUniquekeyRequest) (*QueryGetUniquekeyResponse, error)
	UniquekeyAll(context.Context, *QueryAllUniquekeyRequest) (*QueryAllUniquekeyResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Id(context.Context, *QueryGetIdRequest) (*QueryGetIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Id not implemented")
}
func (UnimplementedQueryServer) IdAll(context.Context, *QueryAllIdRequest) (*QueryAllIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IdAll not implemented")
}
func (UnimplementedQueryServer) Uniquekey(context.Context, *QueryGetUniquekeyRequest) (*QueryGetUniquekeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uniquekey not implemented")
}
func (UnimplementedQueryServer) UniquekeyAll(context.Context, *QueryAllUniquekeyRequest) (*QueryAllUniquekeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniquekeyAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Id_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Id(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Id_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Id(ctx, req.(*QueryGetIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IdAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IdAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IdAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IdAll(ctx, req.(*QueryAllIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Uniquekey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUniquekeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Uniquekey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Uniquekey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Uniquekey(ctx, req.(*QueryGetUniquekeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UniquekeyAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUniquekeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UniquekeyAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UniquekeyAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UniquekeyAll(ctx, req.(*QueryAllUniquekeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.identity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Id",
			Handler:    _Query_Id_Handler,
		},
		{
			MethodName: "IdAll",
			Handler:    _Query_IdAll_Handler,
		},
		{
			MethodName: "Uniquekey",
			Handler:    _Query_Uniquekey_Handler,
		},
		{
			MethodName: "UniquekeyAll",
			Handler:    _Query_UniquekeyAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/identity/query.proto",
}
